config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :categories do
    resources :user_transactions, only: [:index]
  end

  resources :user_transactions, only: [:create, :new]

  get 'all_transactions', to: 'user_transactions#all_transactions', as: :all_transactions

  authenticated :user do

    root to: 'categories#index', as: :authenticated_root

  end

  unauthenticated do
    root to: 'home#index', as: :unauthenticated_root
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    return unless user

    can :manage, Category, user_id: user.id
    can :manage, UserTransaction, author_id: user.id
    can :read, Category # Allow all users to read categories
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :user_transactions, dependent: :destroy
  has_one_attached :icon

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :icon, presence: true

  after_commit :attach_icon_url, if: -> { icon.attached? }

  private

  def attach_icon_url
    host = Rails.env.production? ? 'example.com' : 'localhost:3000'
    update_column(:icon_url, Rails.application.routes.url_helpers.rails_blob_url(icon, host:))
  end
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  has_many :user_transactions, foreign_key: :author_id
  has_many :categories
  validates :name, presence: true, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_transaction.rb
class UserTransaction < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :category
  validates :name, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: exception.message
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]
  load_and_authorize_resource

  def index
    @categories = Category.all
  end

  def show
    authorize! :read, @category
    @total_amount = @category.user_transactions.sum(:amount)
    @transactions = @category.user_transactions.includes(:author, :category).order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.build(category_params)

    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
# app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # No need for any logic here since this is just the default homepage
  end
end

app/controllers/user_transactions_controller.rb
class UserTransactionsController < ApplicationController
  before_action :find_category, only: [:index]

  def index
    @user_transactions = if params[:category_id]
                           @category.user_transactions.includes(:author, :category).order(created_at: :desc)
                         else
                           current_user.categories.joins(:user_transactions).order('user_transactions.created_at DESC')
                             .select('user_transactions.*, categories.name as category_name')
                         end
    @total_amount = @user_transactions.sum(:amount)
  end

  def new
    @user_transaction = UserTransaction.new
    @categories = current_user.categories.includes(:user_transactions)
    @user_transaction.category = Category.find(params[:category_id]) if params[:category_id].present?
  end

  def create
    @user_transaction = UserTransaction.new(user_transaction_params)
    @user_transaction.author = current_user

    if @user_transaction.save
      redirect_to category_user_transactions_path(@user_transaction.category),
                  notice: 'User Transaction was successfully created.'
    else
      @categories = Category.all
      render :new, status: :unprocessable_entity
    end
  end

  private

  def find_category
    @category = Category.find(params[:category_id])
  end

  def user_transaction_params
    params.require(:user_transaction).permit(:name, :amount, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def root_path
    '/'
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/user_transactions_helper.rb
module UserTransactionsHelper
end

app/views/categories/index.html.erb
<div class="container mt-5 pt-5">
  <div class="row">
    <% @categories.each do |category| %>
      <div class="col-6">
        <%= link_to category_user_transactions_path(category), class: 'category-link link' do %>
          <div class="card mb-4" style="height: 250px;"> <!-- Set a fixed height for the card -->
            <div class="row g-0">
              <div class="col-md-8 justify-content-center category-tile">
                <div class="card-body d-flex flex-column align-items-center gap-2 scale-on-hover" style="height: 100%;">
                  <h5 class="card-title link p-text" style="font-size: 18px;"><%= category.name %></h5> <!-- Adjust font size as needed -->
                  <div class="col-md-4 category-image" style="height: 120px;"> <!-- Set a fixed height for the image container -->
                    <%= image_tag(category.icon, class: 'img-fluid rounded-start', style: 'object-fit: contain; height: 100%; width: 100%;') if category.icon.present? %>
                  </div>
                  <p class="card-text link p-text" style="font-size: 16px;">$<%= category.user_transactions.sum(:amount) %></p> <!-- Adjust font size as needed -->
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

  </div>
</div>

<div class="text-center mb-5 bg-green">
  <div class="btn-container border border-white">
    <%= link_to 'add a new category', new_category_path, class: 'btn d-flex flex-column
     mx-2 my-3 text-white justify-content-center border border-white width-95 height-4' %>
  </div>
</div>

app/views/categories/new.html.erb
<!-- app/views/categories/new.html.erb -->

<div class="container mt-5 pt-5">
  <h1 class="mb-4">New Category</h1>

  <%= form_with(model: @category, local: true, html: { class: 'form' }) do |form| %>
    <div class="mb-3">
      <%= form.label :name, "Name", class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :icon, class: 'form-label' %>
      <div class="input-group">
        <%= form.file_field :icon, class: 'form-control' %>
      </div>
    </div>

    <div class="mb-3">
      <%= form.submit 'Save Category', class: 'btn btn-primary' %>
    </div>
  <% end %>

  <%= link_to 'Back', categories_path, class: 'btn btn-secondary' %>
</div>

app/views/home/index.html.erb
<!-- app/views/home/index.html.erb -->
<div class="container-fluid d-flex flex-column align-items-center justify-content-between custom-gap-homepage">
  <div class="title-margin-top">
    <h1>Expense Tracker</h1>
  </div>
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-md-6 d-flex flex-column">
        <%= link_to "Log in", new_user_session_path, class: "btn btn-primary btn-lg btn-block mb-2 rounded-0" %>
        <div class="w-100 text-center">
            <%= link_to "Sign up", new_user_registration_path, class: " p-text link" %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BudgetApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>

<% if user_signed_in? && controller_name == 'user_transactions' && action_name == 'index' %>
  <%= render 'shared/user_transactions_navbar' %>
<% elsif user_signed_in? && controller_name != 'user_transactions' %>
  <!-- Default Navigation Bar -->
  <%= render 'shared/default_navbar' %>
<% elsif controller_name == 'sessions' && action_name == 'new' %>
  <%= render 'shared/sign_in_navbar' %>
<% elsif controller_name == 'user_transactions' && (action_name == 'new' || action_name == 'create') %>
  <%= render 'shared/new_transaction_navbar' %>
<% elsif controller_name == 'registrations' && (action_name == 'new' || action_name == 'create') %>
  <%= render 'shared/sign_up_navbar' %>
<% end %>

<div class="container mb-5 pb-5">
  <div class="text-center mb-5 ">
    <% flash.each do |name, msg| %>
      <% alert_class = name == 'error' ? 'alert-danger' : 'alert-success' %>
      <%= content_tag :div, msg, id: "flash_#{name}", class: "alert #{alert_class}", data: { behavior: "flash" } %>
    <% end %>
  </div>

  <%= yield %>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>

<script>
    document.addEventListener("turbolinks:load", function () {
        // Enable Bootstrap collapse for the navbar
        let navbarToggle = document.querySelector('.navbar-toggler');
        let navbarCollapse = document.querySelector('.navbar-collapse');

        navbarToggle.addEventListener('click', function () {
            if (navbarCollapse.classList.contains('show')) {
                navbarCollapse.classList.remove('show');
            } else {
                navbarCollapse.classList.add('show');
            }
        });

        // Handle click events on nav links
        let navLinks = document.querySelectorAll('.navbar-nav .nav-link');
        navLinks.forEach(function (navLink) {
            navLink.addEventListener('click', function () {
                navbarCollapse.classList.remove('show');
            });
        });
    });
</script>

<script>
    document.addEventListener('turbolinks:load', function() {
        const flashMessages = document.querySelectorAll('[data-behavior="flash"]');

        flashMessages.forEach(flash => {
            setTimeout(() => {
                flash.remove();
            }, 3000); // 3000 milliseconds = 3 seconds
        });
    });

</script>


</body>
</html>

app/views/shared/_default_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light bg-primary text-white ">
  <div class="container-fluid">
    <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon white-icon"></span>
    </button>
    <div class="collapse navbar-collapse vh-100" id="navbarNavAltMarkup" style="max-height: 100vh;">
      <div class="navbar-nav p-text text-white">
        <%= link_to "Home", root_path, class: "nav-link active", "aria-current" => "page" %>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Hi, #{current_user.email}", edit_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link btn btn-unstyled link p-text' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_new_transaction_navbar.html.erb
<!-- Sign In Navigation Bar -->
<nav class="navbar navbar-light bg-light bg-primary text-white">
  <div class="container align-items-baseline">
    <%= link_to :back, class: "navbar-brand" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="white" class="bi bi-arrow-left" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M13.5 8a.5.5 0 0 0-.5-.5H2.707l2.146-2.146a.5.5 0 0 0-.708-.708l-3 3a.5.5 0 0 0 0 .708l3 3a.5.5 0 0 0 .708-.708L2.707 8.5H13a.5.5 0 0 0 .5-.5z"/>
      </svg>
    <% end %>
    <h2 class="navbar-text text-white">NEW TRANSACTION</h2>
  </div>
</nav>

app/views/shared/_sign_in_navbar.erb
<!-- Sign In Navigation Bar -->
<nav class="navbar navbar-light bg-light bg-primary text-white">
  <div class="container align-items-baseline">
    <%= link_to root_path, class: "navbar-brand" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="white" class="bi bi-arrow-left" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M13.5 8a.5.5 0 0 0-.5-.5H2.707l2.146-2.146a.5.5 0 0 0-.708-.708l-3 3a.5.5 0 0 0 0 .708l3 3a.5.5 0 0 0 .708-.708L2.707 8.5H13a.5.5 0 0 0 .5-.5z"/>
      </svg>
    <% end %>
    <h2 class="navbar-text text-white">LOGIN</h2>
    <%= link_to "Log in", "#", class: "btn btn-link text-white link", onclick: "document.getElementById('login-form').submit();" %>
  </div>
</nav>

app/views/shared/_sign_up_navbar.html.erb
<!-- Sign Up Navigation Bar -->
<nav class="navbar navbar-light bg-light bg-primary text-white">
  <div class="container align-items-baseline">
    <%= link_to root_path, class: "navbar-brand" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="white" class="bi bi-arrow-left" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M13.5 8a.5.5 0 0 0-.5-.5H2.707l2.146-2.146a.5.5 0 0 0-.708-.708l-3 3a.5.5 0 0 0 0 .708l3 3a.5.5 0 0 0 .708-.708L2.707 8.5H13a.5.5 0 0 0 .5-.5z"/>
      </svg>
    <% end %>
    <h2 class="navbar-text text-white">REGISTER</h2>
    <%= link_to "Next", "#", class: "btn btn-link text-white link", onclick: "document.getElementById('signup-form').submit();" %>
  </div>
</nav>

app/views/shared/_user_transactions_navbar.html.erb
<!-- User Transactions Index Navigation Bar -->
<nav class="navbar navbar-light bg-light bg-primary text-white d-flex flex-column">
  <div class="container align-items-baseline d-flex justify-content-between">
    <%= link_to root_path, class: "navbar-brand margin-neg-2rem" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="white" class="bi bi-arrow-left" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M13.5 8a.5.5 0 0 0-.5-.5H2.707l2.146-2.146a.5.5 0 0 0-.708-.708l-3 3a.5.5 0 0 0 0 .708l3 3a.5.5 0 0 0 .708-.708L2.707 8.5H13a.5.5 0 0 0 .5-.5z"/>
      </svg>
    <% end %>
    <h2 class="navbar-text text-white ">TRANSACTIONS</h2>
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="white" class="bi bi-search" viewBox="0 0 16 16">
      <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
    </svg>
  </div>
  <div class="container-fluid justify-content-end">
    <div class="sort-transaction d-flex gap-3">
      <p class="text-white">Most recent</p>
      <p class="p-text">Most ancient</p>
    </div>

  </div>
</nav>

app/views/user_transactions/index.html.erb
<div class="container mt-5 pb-5">
  <div class="text-center">
    <h1><%= @category.name %> Transactions</h1>

    <p>Total Amount: $<%= @total_amount %></p>
  </div>

  <!-- List of transactions ordered by most recent -->
  <% @user_transactions.each do |transaction| %>
    <div class="card mb-3 rounded-0">
      <div class="card-body d-flex justify-content-between">
        <div class="transaction-category-image d-flex align-items-center gap-2">
          <div>
            <%= image_tag(transaction.category.icon, width: 100, height: 100) if transaction.category&.icon.present? %>
          </div>
          <div class="d-flex flex-column gap-2">
            <p><%= transaction.name %></p>
            <%= transaction.created_at.strftime('%d %b %Y') %>
          </div>
        </div>
        <div class="d-flex flex-column align-content-center mt-2">
          <p>$<%= transaction.amount %></p>
        </div>
      </div>
    </div>
  <% end %>

  <div class="text-center mb-5 bg-green">
    <div class="btn-container border border-white">
      <%= link_to 'Add a new Transaction', url_for(controller: 'user_transactions', action: 'new'), class: 'btn d-flex flex-column
     mx-2 my-3 text-white justify-content-center border border-white width-95 height-4' %>
    </div>
  </div>

</div>

app/views/user_transactions/new.html.erb
<!-- app/views/user_transactions/new.html.erb -->
<div class="container mt-5 pt-5">
  <h1>Add a new transaction</h1>

<%= form_with(model: @user_transaction, url: user_transactions_path, local: true) do |form| %>

<div class="mb-3">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :amount, class: 'form-label' %>
      <%= form.number_field :amount, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :category_id, class: 'form-label' %>
      <%= form.select :category_id, options_from_collection_for_select(@categories, :id, :name), { prompt: "Select Category" }, class: 'form-control' %>
    </div>

    <div class="mb-3 d-flex justify-content-center w-100">
      <%= form.submit 'Save', class: 'btn btn-primary' %>
    </div>
  <% end %>

</div>